#!/usr/bin/env python3
"""
Generate AI image prompts for blog articles.
Supports DALL-E, Midjourney, and Stable Diffusion.

Usage:
    python generate_ai_image_prompts.py --symbol NVDA --topic blackwell_chip
    python generate_ai_image_prompts.py --list  # List all available prompts
    python generate_ai_image_prompts.py --export all  # Export all prompts
"""

import json
import argparse
from pathlib import Path

# Load AI image prompts
PROMPTS_FILE = Path(__file__).parent / 'ai_image_prompts.json'

def load_prompts():
    """Load AI image prompts from JSON file"""
    with open(PROMPTS_FILE, 'r', encoding='utf-8') as f:
        return json.load(f)

def list_prompts():
    """List all available prompts"""
    prompts = load_prompts()

    print("\n📸 Available AI Image Prompts\n")
    print("=" * 80)

    # Group by symbol
    by_symbol = {}
    for key in prompts.keys():
        symbol = key.split('_')[0]
        if symbol not in by_symbol:
            by_symbol[symbol] = []
        by_symbol[symbol].append(key)

    for symbol in sorted(by_symbol.keys()):
        print(f"\n{symbol}:")
        for prompt_key in sorted(by_symbol[symbol]):
            topic = '_'.join(prompt_key.split('_')[1:])
            print(f"  - {topic}")

    print(f"\n✓ Total: {len(prompts)} prompts available")
    print("=" * 80)

def get_prompt(symbol, topic, model='all'):
    """Get specific prompt for symbol and topic"""
    prompts = load_prompts()

    # Build prompt key
    prompt_key = f"{symbol}_{topic}"

    if prompt_key not in prompts:
        print(f"❌ Prompt not found: {prompt_key}")
        print(f"   Use --list to see available prompts")
        return None

    prompt_data = prompts[prompt_key]

    print(f"\n📸 AI Image Prompts for {symbol} - {topic}")
    print("=" * 80)

    if model == 'all' or model == 'dalle':
        print(f"\n🎨 DALL-E Prompt:")
        print(f"{prompt_data['dalle_prompt']}")

    if model == 'all' or model == 'midjourney':
        print(f"\n🎨 Midjourney Prompt:")
        print(f"{prompt_data['midjourney_prompt']}")

    if model == 'all' or model == 'stable_diffusion':
        print(f"\n🎨 Stable Diffusion Prompt:")
        print(f"{prompt_data['stable_diffusion_prompt']}")

    if model == 'all':
        print(f"\n💡 Style Notes:")
        print(f"{prompt_data['style_notes']}")

    print("\n" + "=" * 80)

    return prompt_data

def export_prompts(output_format='markdown'):
    """Export all prompts to file"""
    prompts = load_prompts()

    if output_format == 'markdown':
        output_file = Path(__file__).parent.parent / 'docs' / 'AI_IMAGE_PROMPTS.md'

        with open(output_file, 'w', encoding='utf-8') as f:
            f.write("# AI Image Generation Prompts\n\n")
            f.write("Professional image prompts for blog article thumbnails.\n\n")
            f.write("**Generated by Codex AI**\n\n")
            f.write("---\n\n")

            # Group by symbol
            by_symbol = {}
            for key, data in prompts.items():
                symbol = key.split('_')[0]
                if symbol not in by_symbol:
                    by_symbol[symbol] = []
                by_symbol[symbol].append((key, data))

            for symbol in sorted(by_symbol.keys()):
                f.write(f"## {symbol}\n\n")

                for prompt_key, prompt_data in sorted(by_symbol[symbol]):
                    topic = ' '.join(prompt_key.split('_')[1:]).title()
                    f.write(f"### {topic}\n\n")

                    f.write("**DALL-E:**\n")
                    f.write(f"```\n{prompt_data['dalle_prompt']}\n```\n\n")

                    f.write("**Midjourney:**\n")
                    f.write(f"```\n{prompt_data['midjourney_prompt']}\n```\n\n")

                    f.write("**Stable Diffusion:**\n")
                    f.write(f"```\n{prompt_data['stable_diffusion_prompt']}\n```\n\n")

                    f.write("**Style Notes:**\n")
                    f.write(f"> {prompt_data['style_notes']}\n\n")

                    f.write("---\n\n")

        print(f"\n✓ Exported {len(prompts)} prompts to {output_file}")

    elif output_format == 'csv':
        import csv
        output_file = Path(__file__).parent.parent / 'docs' / 'ai_image_prompts.csv'

        with open(output_file, 'w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            writer.writerow(['Symbol', 'Topic', 'DALL-E', 'Midjourney', 'Stable Diffusion', 'Style Notes'])

            for key, data in sorted(prompts.items()):
                symbol = key.split('_')[0]
                topic = '_'.join(key.split('_')[1:])
                writer.writerow([
                    symbol,
                    topic,
                    data['dalle_prompt'],
                    data['midjourney_prompt'],
                    data['stable_diffusion_prompt'],
                    data['style_notes']
                ])

        print(f"\n✓ Exported {len(prompts)} prompts to {output_file}")

def copy_to_clipboard(text):
    """Copy text to clipboard (macOS)"""
    try:
        import subprocess
        subprocess.run(['pbcopy'], input=text.encode('utf-8'), check=True)
        print("\n✓ Copied to clipboard!")
    except:
        print("\n⚠️  Could not copy to clipboard (macOS only)")

def main():
    parser = argparse.ArgumentParser(description='Generate AI image prompts for blog articles')
    parser.add_argument('--symbol', type=str, help='Stock symbol (e.g., NVDA, AAPL)')
    parser.add_argument('--topic', type=str, help='Topic (e.g., blackwell_chip, robotaxi)')
    parser.add_argument('--model', type=str, choices=['all', 'dalle', 'midjourney', 'stable_diffusion'],
                        default='all', help='AI model to generate prompt for')
    parser.add_argument('--list', action='store_true', help='List all available prompts')
    parser.add_argument('--export', type=str, choices=['markdown', 'csv', 'all'],
                        help='Export all prompts to file')
    parser.add_argument('--copy', action='store_true', help='Copy prompt to clipboard')

    args = parser.parse_args()

    if args.list:
        list_prompts()
    elif args.export:
        if args.export == 'all':
            export_prompts('markdown')
            export_prompts('csv')
        else:
            export_prompts(args.export)
    elif args.symbol and args.topic:
        prompt_data = get_prompt(args.symbol.upper(), args.topic.lower(), args.model)

        if prompt_data and args.copy:
            # Copy to clipboard based on model
            if args.model == 'dalle':
                copy_to_clipboard(prompt_data['dalle_prompt'])
            elif args.model == 'midjourney':
                copy_to_clipboard(prompt_data['midjourney_prompt'])
            elif args.model == 'stable_diffusion':
                copy_to_clipboard(prompt_data['stable_diffusion_prompt'])
            else:
                # Copy all prompts
                all_text = f"DALL-E:\n{prompt_data['dalle_prompt']}\n\n"
                all_text += f"Midjourney:\n{prompt_data['midjourney_prompt']}\n\n"
                all_text += f"Stable Diffusion:\n{prompt_data['stable_diffusion_prompt']}\n\n"
                all_text += f"Style Notes:\n{prompt_data['style_notes']}"
                copy_to_clipboard(all_text)
    else:
        parser.print_help()

if __name__ == '__main__':
    main()
